---
all:
  children:
    routers:
      children:
        core:
          hosts:
            R1:
              ansible_host: 172.16.92.101
            R2:
              ansible_host: 172.16.92.102
            R3:
              ansible_host: 172.16.92.103
        edge:
          hosts:
            R4:
              ansible_host: 172.16.92.104
            R5:
              ansible_host: 172.16.92.105
    switches:
      children:
        customer_prem:
          hosts:
            SW1:
              ansible_host: 172.16.92.201
            SW2:
              ansible_host: 172.16.92.202

